export enum Operation {
  FILE_READ = "FILE.READ",
  FILE_WRITE = "FILE.WRITE",
  NETWORK = "NETWORK",
  ENVIRONMENT_READ = "ENVIRONMENT.READ",
  ENVIRONMENT_WRITE = "ENVIRONMENT.WRITE",
  USER = "USER",
}
